**Import Library**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

**Model**

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

**Load DATA**

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# New section

# New section

In [4]:
df = pd.read_csv("/content/drive/MyDrive/dataset/Descriptors.csv")
df

,pIC50,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,4.004892,-0.3240,0.104976,10.5451,27.871551,6,6,21,14,7,...,9.762845,28.229061,2.016362,11.016089,5.042900,2.956971,314,16,2.925,70
1,3.420102,0.9086,0.825554,23.8407,30.298344,6,6,23,15,8,...,9.479460,30.087052,2.005803,11.017342,5.043334,2.957234,387,18,3.502,76
2,3.468904,0.1557,0.024242,11.4176,27.761758,6,6,21,15,6,...,10.619539,30.087052,2.005803,13.537212,5.043334,2.957234,387,18,1.829,76
3,3.806041,0.5648,0.318999,19.1442,30.254758,6,6,21,15,6,...,13.472870,30.087052,2.005803,13.537212,5.043334,2.957234,387,18,2.304,76
4,4.070837,1.1646,1.356293,21.7763,30.897965,6,6,21,16,5,...,12.997229,31.934587,1.995912,16.074381,5.042973,2.957015,448,21,2.062,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,5.044312,0.9828,0.965896,36.2771,53.522723,20,22,40,29,11,...,10.625631,60.364692,2.081541,32.827381,10.576771,15.981493,2371,46,4.156,162
103,4.274088,1.4208,2.018673,38.8217,54.249723,20,22,41,30,11,...,10.927501,62.136726,2.071224,32.104003,5.738924,12.946934,2527,48,5.594,170
104,6.677781,0.5810,0.337561,57.8307,66.428653,20,22,53,32,21,...,8.813369,66.226728,2.069585,30.803251,8.315470,16.218559,3092,53,3.751,176
105,4.486782,1.7271,2.982874,41.8927,55.035930,20,22,40,30,10,...,11.474657,62.214397,2.073813,35.373455,10.576758,15.982096,2527,49,4.252,168
106,4.922269,1.7271,2.982874,41.8927,55.035930,20,22,40,30,10,...,11.474657,62.214397,2.073813,35.373455,10.576758,15.982096,2527,49,4.252,168

In [5]:
print(df.columns)

Index(['pIC50', 'ALogP', 'ALogp2', 'AMR', 'apol', 'naAromAtom', 'nAromBond',
       'nAtom', 'nHeavyAtom', 'nH',
       ...
       'AMW', 'WTPT-1', 'WTPT-2', 'WTPT-3', 'WTPT-4', 'WTPT-5', 'WPATH',
       'WPOL', 'XLogP', 'Zagreb'],
      dtype='object', length=1043)

**Checking for Null Values**

In [6]:
df.isnull()

,pIC50,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
103,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
104,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
105,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
106,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

pIC50     0
ALogP     0
ALogp2    0
AMR       0
apol      0
         ..
WTPT-5    0
WPATH     0
WPOL      0
XLogP     0
Zagreb    0
Length: 1043, dtype: int64

In [8]:
df.isnull().sum().sum()

4125

In [9]:
df2 = df.fillna(value = 0) 
df2

,pIC50,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,4.004892,-0.3240,0.104976,10.5451,27.871551,6,6,21,14,7,...,9.762845,28.229061,2.016362,11.016089,5.042900,2.956971,314,16,2.925,70
1,3.420102,0.9086,0.825554,23.8407,30.298344,6,6,23,15,8,...,9.479460,30.087052,2.005803,11.017342,5.043334,2.957234,387,18,3.502,76
2,3.468904,0.1557,0.024242,11.4176,27.761758,6,6,21,15,6,...,10.619539,30.087052,2.005803,13.537212,5.043334,2.957234,387,18,1.829,76
3,3.806041,0.5648,0.318999,19.1442,30.254758,6,6,21,15,6,...,13.472870,30.087052,2.005803,13.537212,5.043334,2.957234,387,18,2.304,76
4,4.070837,1.1646,1.356293,21.7763,30.897965,6,6,21,16,5,...,12.997229,31.934587,1.995912,16.074381,5.042973,2.957015,448,21,2.062,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,5.044312,0.9828,0.965896,36.2771,53.522723,20,22,40,29,11,...,10.625631,60.364692,2.081541,32.827381,10.576771,15.981493,2371,46,4.156,162
103,4.274088,1.4208,2.018673,38.8217,54.249723,20,22,41,30,11,...,10.927501,62.136726,2.071224,32.104003,5.738924,12.946934,2527,48,5.594,170
104,6.677781,0.5810,0.337561,57.8307,66.428653,20,22,53,32,21,...,8.813369,66.226728,2.069585,30.803251,8.315470,16.218559,3092,53,3.751,176
105,4.486782,1.7271,2.982874,41.8927,55.035930,20,22,40,30,10,...,11.474657,62.214397,2.073813,35.373455,10.576758,15.982096,2527,49,4.252,168
106,4.922269,1.7271,2.982874,41.8927,55.035930,20,22,40,30,10,...,11.474657,62.214397,2.073813,35.373455,10.576758,15.982096,2527,49,4.252,168

In [10]:
df2.isnull().sum().sum()

0

**Input and Output Preparation**

In [11]:
X = df2.drop(['pIC50'],axis = 1)
X

,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,nC,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,-0.3240,0.104976,10.5451,27.871551,6,6,21,14,7,10,...,9.762845,28.229061,2.016362,11.016089,5.042900,2.956971,314,16,2.925,70
1,0.9086,0.825554,23.8407,30.298344,6,6,23,15,8,11,...,9.479460,30.087052,2.005803,11.017342,5.043334,2.957234,387,18,3.502,76
2,0.1557,0.024242,11.4176,27.761758,6,6,21,15,6,10,...,10.619539,30.087052,2.005803,13.537212,5.043334,2.957234,387,18,1.829,76
3,0.5648,0.318999,19.1442,30.254758,6,6,21,15,6,10,...,13.472870,30.087052,2.005803,13.537212,5.043334,2.957234,387,18,2.304,76
4,1.1646,1.356293,21.7763,30.897965,6,6,21,16,5,10,...,12.997229,31.934587,1.995912,16.074381,5.042973,2.957015,448,21,2.062,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,0.9828,0.965896,36.2771,53.522723,20,22,40,29,11,18,...,10.625631,60.364692,2.081541,32.827381,10.576771,15.981493,2371,46,4.156,162
103,1.4208,2.018673,38.8217,54.249723,20,22,41,30,11,19,...,10.927501,62.136726,2.071224,32.104003,5.738924,12.946934,2527,48,5.594,170
104,0.5810,0.337561,57.8307,66.428653,20,22,53,32,21,22,...,8.813369,66.226728,2.069585,30.803251,8.315470,16.218559,3092,53,3.751,176
105,1.7271,2.982874,41.8927,55.035930,20,22,40,30,10,18,...,11.474657,62.214397,2.073813,35.373455,10.576758,15.982096,2527,49,4.252,168
106,1.7271,2.982874,41.8927,55.035930,20,22,40,30,10,18,...,11.474657,62.214397,2.073813,35.373455,10.576758,15.982096,2527,49,4.252,168

In [12]:
Y = df2.pIC50
Y

0      4.004892
1      3.420102
2      3.468904
3      3.806041
4      4.070837
         ...
102    5.044312
103    4.274088
104    6.677781
105    4.486782
106    4.922269
Name: pIC50, Length: 107, dtype: float64

**Initiation of Recursive Feature Elimination (RFE) for Random Forest Regressor**

In [14]:
rfr = RandomForestRegressor(random_state=30)
sel = RFE(estimator=rfr, n_features_to_select=50)
sel.fit(X, Y)
sel.get_support()

array([False, False, False, ..., False, False, False])

In [15]:
len(sel.get_support())

1042

In [16]:
features = X.columns[sel.get_support()]

In [17]:
features

Index(['ATS5m', 'ATSC8p', 'AATSC0m', 'AATSC6m', 'AATSC1v', 'AATSC2i',
       'AATSC7i', 'MATS4c', 'MATS1s', 'GATS4v', 'GATS3e', 'GATS3s', 'VR3_DzZ',
       'VR3_Dzm', 'VR3_Dzp', 'VE1_Dzi', 'SpMax5_Bhm', 'SpMax6_Bhm',
       'SpMax1_Bhv', 'SpMin1_Bhv', 'SpMin5_Bhv', 'SpMax6_Bhe', 'SpMax1_Bhp',
       'SpMax4_Bhp', 'SpMin8_Bhp', 'SpMax1_Bhi', 'SpMax4_Bhi', 'SpMax6_Bhi',
       'SpMin4_Bhs', 'SpMin5_Bhs', 'CrippenLogP', 'CrippenMR', 'VR3_Dt',
       'SaaN', 'SsssN', 'SsCl', 'minHBa', 'minHCsats', 'maxaaN', 'hmin',
       'LipoaffinityIndex', 'CIC1', 'MDEO-12', 'MDEO-22', 'R_TpiPCTPC', 'JGI8',
       'TopoPSA', 'MWC9', 'SRW10', 'WTPT-5'],
      dtype='object')

In [18]:
len(features)

50

In [19]:
print(sel.ranking_)

[110  25 561 ... 857  27 962]

In [20]:
feature_importance = pd.DataFrame({"Feature_Name" : X.columns[sel.get_support()]})
feature_importance

         Feature_Name
0               ATS5m
1              ATSC8p
2             AATSC0m
3             AATSC6m
4             AATSC1v
5             AATSC2i
6             AATSC7i
7              MATS4c
8              MATS1s
9              GATS4v
10             GATS3e
11             GATS3s
12            VR3_DzZ
13            VR3_Dzm
14            VR3_Dzp
15            VE1_Dzi
16         SpMax5_Bhm
17         SpMax6_Bhm
18         SpMax1_Bhv
19         SpMin1_Bhv
20         SpMin5_Bhv
21         SpMax6_Bhe
22         SpMax1_Bhp
23         SpMax4_Bhp
24         SpMin8_Bhp
25         SpMax1_Bhi
26         SpMax4_Bhi
27         SpMax6_Bhi
28         SpMin4_Bhs
29         SpMin5_Bhs
30        CrippenLogP
31          CrippenMR
32             VR3_Dt
33               SaaN
34              SsssN
35               SsCl
36             minHBa
37          minHCsats
38             maxaaN
39               hmin
40  LipoaffinityIndex
41               CIC1
42            MDEO-12
43            MDEO-22
44         R_TpiPCTPC
45               JGI8
46            TopoPSA
47               MWC9
48              SRW10
49             WTPT-5

In [21]:
np.mean(sel.estimator_.feature_importances_)

0.02

In [22]:
sel.estimator_.feature_importances_

array([0.01020807, 0.00965461, 0.00973654, 0.01044778, 0.01093642,
       0.014484  , 0.00881296, 0.01465283, 0.01157576, 0.02245602,
       0.00891356, 0.01205531, 0.02927817, 0.00977036, 0.03260748,
       0.13991252, 0.02506094, 0.02064997, 0.02575256, 0.013219  ,
       0.00956766, 0.02789642, 0.01324615, 0.02878541, 0.00997731,
       0.0144215 , 0.01749034, 0.03822612, 0.01668611, 0.01284675,
       0.01831789, 0.01475063, 0.01006455, 0.01212524, 0.01226995,
       0.01275015, 0.00837655, 0.09553476, 0.01035376, 0.02952649,
       0.02446607, 0.00878   , 0.01565932, 0.01210506, 0.01932465,
       0.01118509, 0.0127782 , 0.0208972 , 0.01070463, 0.01070118])